### ISSUE TITLE
Fix Error passing in BlockOperation

### ISSUE THREAD

**Issue by gav5** [doubleencore/MPA-Horatio#18]
`BlockOperation(block:)` is not piping the error param into the finish call, causing these operations to always succeed.

To correct, this should change this code (BlockOperation.swift:52):
```swift
override open func execute() {
    guard !isCancelled else {
        finish()
        return
    }
    
    block { _ in
        self.finish()
    }
}
```

Instead, this should look as follows:
```swift
override open func execute() {
    guard !isCancelled else {
        finish()
        return
    }
    
    block { error in
        self.finishWithError(error)
    }
}
```

**Comment by kpcwatson** [comment]
It looks like that code hasn't been touched in over 2 years. It's surprising no one has raised this issue already. 

@gav5 can you submit a PR?

**Comment by kpcwatson** [comment]
We'll also need to tag this as a minor release as I assume it could have side effects across projects.

**Comment by gav5** [comment]
@kpcwatson I tried to submit a PR and was denied access
